### PR TITLE
Enhances fetch requests to include credential cookies

### PR DESCRIPTION
**Pull request by evolve2k**
Resolves https://github.com/dixieio/redux-json-api/issues/65

Calls to fetch just need to have credentials: 'include', added to them to once again pass credential information across like jQuery ajax requests do by default.

Reference: https://developers.google.com/web/updates/2015/03/introduction-to-fetch#sending-credentials-with-a-fetch-request

> Sending Credentials with a Fetch Request
> 
> Should you want to make a fetch request with credentials such as cookies, you should set the credentials of the request to “include”.
> 
> fetch(url, {  
>   credentials: 'include'  
> })

### CODE REVIEW

**Comment by evolve2k** [comment]
@egeriis As I've mentioned my JS skills are limited so if you're willing to enhance this yourself if you see any issues with it, that'd be greatly appreciated.

**Comment by evolve2k** [comment]
@egeriis oh just adding to read also, yeah actually I can do that! Just a moment.

**Comment by evolve2k** [comment]
> Looks like you're missing the option on readEndpoint :)
@egeriis Added!

**Comment by evolve2k** [comment]
Fixing lint issues now.

**Comment by egeriis** [comment]
Great. Will merge and publish as v1.5.4.

**Comment by egeriis** [comment]
Published to npm

**Comment by evolve2k** [comment]
Wooo! Thx so much!

**Comment by gazpachu** [comment]
Setting a cookie in the header still doesn't work :(

```
this.props.dispatch(setHeader({
	'Cookie': String(document.cookie)
}));
```

**Pull request merged**
