### PR TITLE
Deprecate old API methods

### LINKED ISSUE #85: Deprecate old methods
As per suggestion in #84, to prepare users of v1.x for upgrade to v2.0, old API method names will now be deprecated and note that they will be removed in v2.0.

### PR DESCRIPTION
**Pull request by egeriis**
Resolves #85

### CODE REVIEW

**Comment by egeriis** [comment]
@nopzen Would you care to review and test this? :)

**Comment by Nopzen** [comment]
Ill have a look later today. @egeriis

**Comment by egeriis** [comment]
@Nopzen Did you have a chance to look at this?

**Comment by Nopzen** [comment]
@egeriis no, completely forgotten. Let me have a look now.

**Comment by Nopzen** [comment]
@egeriis LGTM.

**Comment by egeriis** [comment]
Awesome, thanks @Nopzen

**Pull request merged**
