### PR TITLE
Preserve order of collection when updating an object.

### PR DESCRIPTION
**Pull request by Petesta**

### CODE REVIEW

**Comment by Petesta** [comment]
This PR aims to preserve the ordering of a collection when making an update and references this [issue](https://github.com/dixieio/redux-json-api/issues/73).

Currently, after making an update this what the response will come back as.

```javascript
const state = [ { type: 'users',
    id: '1',
    attributes: { name: 'John Doe' },
    relationships: { companies: [Object] } },
  { type: 'users',
    id: '2',
    attributes: { name: 'Emily Jane' },
    relationships: { companies: [Object] } } ];

const updatedState = [ { type: 'users',
    id: '2',
    attributes: { name: 'Emily Jane' },
    relationships: { companies: [Object] } },
  { type: 'users',
    id: '1',
    attributes: { name: 'Sir John Doe' },
    relationships: { tasks: [Object] } } ];
```

With the preservation of order here is what we get.

```javascript
const state = [ { type: 'users',
    id: '1',
    attributes: { name: 'John Doe' },
    relationships: { companies: [Object] } },
  { type: 'users',
    id: '2',
    attributes: { name: 'Emily Jane' },
    relationships: { companies: [Object] } } ]
const updatedState = [ { type: 'users',
    id: '1',
    attributes: { name: 'Sir John Doe' },
    relationships: { tasks: [Object] } },
  { type: 'users',
    id: '2',
    attributes: { name: 'Emily Jane' },
    relationships: { companies: [Object] } } ]
```

**Comment by egeriis** [comment]
Would've loved to see the test in a commit before the fix, then it's easier to review that it's failing without your fix :)

**Comment by Petesta** [comment]
@egeriis Can you clarify your strategy here? Do you want me to submit a failing test, you look at it, then I fix it or just create a new test and merge?

**Comment by egeriis** [comment]
@Petesta No action needed for this. But if you are making two separate commits, first one is a failing test the next one is the fix. That should prompt GitHub to display that the first commit has a failing test and that the next one resolves this :)

**Comment by egeriis** [comment]
Example: 
image

**Comment by egeriis** [comment]
We will merge and publish today :)

**Comment by egeriis** [comment]
Published to npm

**Pull request merged**
