### PR TITLE
Add .nvmrc to .gitignore

### PR DESCRIPTION
**Pull request by asiniy**
I'm the person who's using node version manager, https://github.com/creationix/nvm . I set up `.nvmrc` file for every js project, but I don't think I have to commit it here...

### CODE REVIEW

**Comment by asiniy** [comment]
@egeriis @Nopzen ?

**Comment by egeriis** [comment]
I'm not sure it makes sense to add `.nvmrc` to `.gitignore` if we don't have that file in the repo. We could surely add it to the lib, but I don't understand why nvm doesn't read from `package.json`, which provides the dependent Node version?

**Comment by asiniy** [comment]
@egeriis `.nvmrc` is a development file. Like `IDEA` files, are you sure you want to track them?

**Comment by egeriis** [comment]
@asiniy No, of course not :) I was a bit confused about the purpose, but I understand your point now. Let's merge this in :)

**Comment by asiniy** [comment]
Thanks!

**Pull request merged**
