### PR TITLE
adding link to Quickstart guide showing how to implement the library …

### PR DESCRIPTION
**Pull request by tomharvey**
In response to discussion on https://github.com/dixieio/redux-json-api/issues/99

### CODE REVIEW

**Comment by Nopzen** [comment]
Hi @tomharvey

Thanks for the contribution, i'll just quickly ensure that the link is working, and the test is workign with the given steps, then ill get back to you.

**Comment by tomharvey** [comment]
Thanks @Nopzen I'll have a look at the dependancies issues.

I was planning to keep the creation of an api server out of scope as this is meant to be seen as a tutorial on using redux-son-api to create a client.

That said I've also considered throwing the example JSON into S3 and serving it out of there, this would allow for full testing and playing without too much yak shaving. I doubt the transfer costs on this example JSON file will be noticeable and it sounds like there is a benefit in use and clarity if there is an API server provided for the user. What do you think?

**Comment by Nopzen** [comment]
Hi @tomharvey 

The dependency issue is probably a good idea :p since the package missing is set 📦  you want to write a guide for.

For the serving of the data, I think it's important for the user to see data actually getting in, they don't need to understand how the server gets it there but just need to know that when then use the `readEndpoint` from the tool it will get data, and also post or update this.

Feel free to take my implementation if you want form my own little example repo I might need to abandon since time is my concern right now: 

https://github.com/Nopzen/redux-json-api/tree/api-example/example

As my memory serve's me i think the express server should be running fine.

**Comment by tomharvey** [comment]
@Nopzen I've fixed the dependancy issue and I've added the ability to actually run the test code.

We've already got webpack-dev-server running, so I've just used this to serve up the JSON as well. Given that it's on the same hostname I don't need to go into any conversation about cors in the tutorial and the user can have an 'api server' without doing any additional work.

let me know what you think. Thanks

**Comment by Nopzen** [comment]
Hi @tomharvey 

I'll have a look again later today. :)

**Comment by Nopzen** [comment]
Hi @tomharvey 

I'm not ther person who should proof read, but i found a pretty big mistake, in this section:
__Imports__
_We now need to import more than just the basic `react` and react-don_
This should proberly be `react-dom` to eliminate any confussion

Besides this, i find the guide okay, and the working example okay just for debugging and see how the tool operates on the `readEndpoint` of things.

I assume the this guide like you state is just to implement, not to use tool, for this im okay with this guide.

**Comment by tomharvey** [comment]
Yip - it's intended as a guide on how to get up and running with readEndpoint, more of a quickstart than a detailed api documentation (which you've provided in the repo) or an opinion on how to implement the library in a production app. To achieve this I've tried to create the minimum amount of code that will make use of the library and run as an app. Hopefully this will allow others to quickly start probing the capabilities of redux-json-api and start using it.

Ooops - I'll get on that dom/don typo, thanks!

**Comment by Nopzen** [comment]
Cool beans ☕️ 

Fix the typo, and i'll run it down in master.

**Comment by tomharvey** [comment]
Typo fixed 👍 

I'd love to see a fuller, opinionated guide on how to best implement the library in a production app; with all of CRUD operations covered and guidelines on best practices and patterns for development. I'm just hacking away on my first production deploy of this library myself, so I'm far from capable of writing this. Also, I've found that the community around React and ES6, while great, is still young and so agreement on the best patterns to use changes frequently.

If you know of any open source applications using the library that might be a good, quick source of a fuller guide to implementation of the library.

Thanks for the review! Hopefully enough people get some use of the guide that others will pop issues up and suggestions.

**Comment by Nopzen** [comment]
@tomharvey - merged

I dont know personaly any open source projects using us, but i can easily get behind your thoughts, we here at @Dixie have some guidelines how we use it in _production_ and maybe we could write some more info about this in either a blog post or a wiki for the project not sure.

But thank you for you basic getting started guide!

**Comment by egeriis** [comment]
@tomharvey Some thoughts on best practices:

We've been using this library for around a year now—since we established it. But only recently have we met the performance hits that could come from having a large application. This is not exclusive to redux-json-api, but certainly a great resource to share for people who are using this library.

Some of the knowledge that we've gathered is to use `reselect` for querying the data and avoid `connect`ing too many components to read from Redux state.

We're working to get some common `reselect` selectors to share as open source, but currently we only have 2: 

1. Select resources of a certain type from state
1. Select a particular resource from type and ID

Just to provide you with our experience, some inspirational thoughts.

**Comment by tomharvey** [comment]
Sounds like a good starting point, love to see the future shared selectors. Thanks

**Pull request merged**
