### PR TITLE
Rename API method names to fit JSON API spec taxonomy

### LINKED ISSUE #83: Change API names to be spec-compatible
Currently we use the term "entity" which is not in line with JSON API documentation, which uses the term "resource". This should be updated so there are no confusion around the taxonomy.

### PR DESCRIPTION
**Pull request by egeriis**
Resolves #83

### CODE REVIEW

**Comment by evolve2k** [comment]
Nice one. I think this is a worthwhile yet significant breaking change.

How about including alias to the existing API methods that map directly to the new method names but also then include a deprecation warning in the console.

I think then it would be fine to roll this out now, as the current API would not break only start issue deprecation warnings in addition to working as expected.

2 cents.

**Comment by egeriis** [comment]
The idea is for this to be merged into v2.0.

But I like your idea of adding a deprecation note for next v1.x. We'll do that :)

**Comment by egeriis** [comment]
@evolve2k Opened #86 to fix this :)

**Comment by lifeiscontent** [comment]
@egeriis when do you think 2.0 will be finished? Is there something I can help with? I'd like to get this working with OPTIONS requests and CORS.

**Comment by Nopzen** [comment]
@lifeiscontent 

Im working on wrapping it up this week, sorry for the late reply, main issue is this axios update #68 

So hopefully i will have i stable by friday.

**Pull request merged**
