### PR TITLE
Null data in related resource

### PR DESCRIPTION
**Pull request by Mory1879**
For #196 issue

### CODE REVIEW

**Comment by KODerFunk** [comment]
@dakota hi! Can you review this bug-fix, merge and publish new version?

**Review by dakota — APPROVED** [review]

**Comment by dakota** [comment]
> @dakota hi! Can you review this bug-fix, merge and publish new version?

Hey, I completely missed this 😱

**Comment by dakota** [comment]
I will publish a new release as soon as I have a moment at my computer

**Comment by Mory1879** [comment]
Hi, @dakota. Any luck?

**Comment by KODerFunk** [comment]
@dakota hi! Do you have time to release a new version now? 
We want to include this library in our company in recommendation, but without this correction in regular release we cannot do this.

**Comment by Jonniedev** [comment]
Since this is already in master you can install from github rather than from npm.

Step 1.
`yarn add https://github.com/redux-json-api/redux-json-api` 
(this points to master, so you will get this PR code

Step 2.
`cd node_modules/redux-json-api`
Step 2.1
`yarn install`
(will build the lib dir)
Step 2.2.
`yarn install --production`
(will cleanup the huge nested node_modules there)

**Pull request merged**
