### PR TITLE
Update readEndpoint.md

### PR DESCRIPTION
**Pull request by marcw**

### CODE REVIEW

**Comment by egeriis** [comment]
I reckon that the path passed to `readEndpoint` is naively concat'ed with the path set through `setEndpointPath`, so I am not sure this makes a huge difference for documenting redux-json-api. What are your motivation for this, @marcw? :)

**Comment by marcw** [comment]
Hi !

Sorry for the lack of information in this PR. My motivation is correctness of the documentation. If you see the code example below, the leading `/` is absent whereas it is present in the part of the documentation I fix with this PR. I spent a few minutes debugging because of that. I just wanted to alleviate that pain to other people ! :)

**Comment by egeriis** [comment]
Sure thing. Let's get this in then. Thank you @marcw :)

**Comment by marcw** [comment]
Thank you!

**Pull request merged**
