### PR TITLE
Allow any headers in requests

### PR DESCRIPTION
**Pull request by adz**
I needed to have CSRF tokens submitted as part of a section of a 'mostly' server side HTML rails app. I updated the docs with how it works, and left 'setAccessToken' action intact.

### CODE REVIEW

**Comment by egeriis** [comment]
LGTM. Will test later today :)

Please note that v2.0 will feature an update to Axios, which will make extending the request much more flexible :)

**Comment by egeriis** [comment]
Merged and published to NPM as v1.5.0.

Sorry for the late acting. Must've had my attention taken away by something else :)

**Comment by adz** [comment]
No probs -- i noticed a minor fault in the docs I changed. If you don't set a host/endpoint things don't work, but I wrote that it defaults to root ('/').

Also, I ended up having to hack in "credentials: include" as we're using cookie sessions, and `fetch` needs this explicitly.... However I haven't had time to get a PR ready.

How far are you from the v2.0 version?
I could play with that instead if it'd' be more useful to you.

**Comment by egeriis** [comment]
Not far from release. But we're awaiting a revision of #41. It seems that the developer has disappeared though, so we'll need to revise it ourselves or have some other contributor help. If you feel like reviewing the PR, you're very welcome :)

**Comment by gazpachu** [comment]
> hack in "credentials: include" as we're using cookie sessions, and fetch needs this explicitly

@adz do you mind letting me know in which file I can make that change? I cannot find the `fetch` folder in my `node_modules`. Thanks!

**Comment by egeriis** [comment]
@gazpachu Are you sure that's the correct header name? I'm pretty sure that it's "Set-Cookie" for requests. Does the four header show up in your request?

**Comment by gazpachu** [comment]
Yes, it works fine in the staging environment. The issue seems to happen only in localhost with webpack web server, so that's it. There's no problem :)

**Comment by adz** [comment]
Good to hear, as I thought the hack is not necessary any more.

-----Original Message-----

**Pull request merged**
