### PR TITLE
Add ability to read from JSON blobs

### PR DESCRIPTION
**Pull request by berfarah**
There are times when you may already have a `JSON` blob that you want `redux-json-api` to work with. In those cases, there is currently no way without using internal APIs to add it to the api state.

Example use-cases are:
1. Hydrating data via `JSON` blob that is passed in with the application
2. Websockets passing in data that a user wants to consume using this package

My proposal is to introduce `readBlob` (open to renaming - maybe `readJSON`?), which takes a JSON-API object and adds it to the state.

I'm happy to add tests, reword or refactor as you guys see fit.

### CODE REVIEW

**Comment by berfarah** [comment]
The build looks to be failing - but not from any changes I made :\

**Comment by Nopzen** [comment]
Hi @berfarah 

 - We are aware that the build is failing, we are currently working on `v2.0` release where these tests should get fixed. After the release i think we will look back to your PR :) sorry for the delay.

**Comment by berfarah** [comment]
@Nopzen cool beans, good to know, thanks! Looking forward to your opinion/feedback on this!

**Comment by Nopzen** [comment]
Hi @berfarah 

I looks pretty straight forward what you want, and im not a big opposer to why this should not be able to be handled, but just to understand your use case:

You have a `JSON-API` spec'ed blob some where or generating them, and you want the tool to pass these into the sate? - Is there a reason for why these are not created with the `createResource` api and then appended to the state that way? this also ensures that your database would be up to date and the view would not be wiped on refresh ? :)

On another note we release the `v2.0.0` beta, could it be possible for you to maybe work of that branch instead the branch is named `2.0` because im not sure we are gonna implement new features in a soon to be deprecated version `v1.x`

**Comment by berfarah** [comment]
@Nopzen Happy to move this to the 2.0 release branch.

Happy to clarify my usecase :). This is for when the data already exists in the database and I want the frontend to be pre-loaded with some data without having to make a separate call. For example, I load the page with:

```html
<html><body>
  <div id="app"></div>
  <script>window.__INIT__ = {"data": ...}</script>
</body></html>
```

I want to load the JSON blob from `window.__INIT__` directly into the store without making a separate call.

There's also the potential for passing data via websockets, but the above is really my primary usecase.

**Comment by berfarah** [comment]
@Nopzen I've rebased it on 2.0 - would you like me to re-open this PR on 2.0 or do you prefer me waiting until that's merged?

**Comment by Nopzen** [comment]
Hey @berfarah 

Now i see your use case, and the idea is okay enough, but i think of a better approch how we could hydrate the state initially.

Im thinking that we in the reducer of the `redux-json-api` could just append the data from the window variable if its set on application init like so:

```js
// jsonapi.js - reducer
{
  isCreating: 0,
  isReading: 0,
  isUpdating: 0,
  isDeleting: 0,
  endpoint: {
    axiosConfig: {}
  }
  ... window.__INIT-REDUX-JSON-API__
}
```

The code above is very psuedo code here to illustrate the idea, but i think this would be more beneficial for you applicaiton as it dos not need to load the lib, then run a action to then return and load your app.

If you can come up with an idea, and tests to cover this, i would be happy to look back at it since i dont thing going with an extra api is the way to go :)

Regarding opening a new PR, yes please open one in to `2.0` branch and refrence this PR so we can keep track of the discussion

We can merge this into `2.0` if we find this stable after some time,  ill quickly fix the travis build errors now so you can count on travis reports to see if there is errors with your code.

**Comment by berfarah** [comment]
@Nopzen Thanks for responding! I'll open a new PR soon incorporating your feedback.

One thing I want to note:
I'm fine with making a global variable on window that we pull from to hydrate the store. One thing that I want to make sure of is that you're ok with preprocessing the data before putting it in the reducer.

The reason I'd want to pre-process it is that currently, there's a specific format to how you get resources from the store `[type]: [{}]`. I would prefer hydration data to be in a standard JSON-API format, and not have to know about the way that `redux-json-api` likes to store that data.

My proposal is to do something like:

```js
// constants
const API_HYDRATE = 'API_HYDRATE';

// action
const apiHydrate = createAction(API_HYDRATE);

// reducer
[API_HYDRATE]: 
```

**Comment by berfarah** [comment]
@Nopzen Thanks for responding! I'll open a new PR soon incorporating your feedback.

One thing I want to note:
I'm fine with making a global variable on window that we pull from to hydrate the store. One thing that I want to make sure of is that you're ok with preprocessing the data before putting it in the reducer.

The reason I'd want to preprocess it is that currently, there's a specific format to how you get resources from the store `[type]: [{}]`. I would prefer hydration data to be in a standard JSON-API format, and not have to know about the way that `redux-json-api` likes to store that data. From my perspective, this also falls in line with the library's goals of handling the Redux<>JSON-API barrier.

My proposal is to do something like:

```js
// constants
const API_HYDRATE = 'API_HYDRATE';

// action
export const apiHydrate = createAction(API_HYDRATE);

// reducer
{
  [API_HYDRATE]: (state, { payload }) => {
    if (!payload) return state;

    const resources = (
      Array.isArray(payload.data)
        ? payload.data
        : [payload.data]
    ).concat(payload.included || []); // extract this into a utility function since it's called a few times in the reducer

    const newState = updateOrInsertResourcesIntoState(state, resources);
    const finalState = addLinksToState(newState, payload.links, payload.options);

    return imm(finalState).value();
  },
  // initial state
  {
    // stuff
    ...apiHydrate(window.__INIT_JSON_API_REDUX__) // assuming this doesn't create a circular dependency
  }
}
```

If the above actually works (it's _more or less_ code, I'm not sure if there are circular dependencies/infinite loops here), this would allow us to handle both scenarios: when a user wants to hydrate before loading the library and when the user wants to hydrate the library themselves / doesn't want to pollute the global namespace.

**Comment by Nopzen** [comment]
Hi @berfarah 

Sure that sounds like some thing we could try out at first, i like the comment:
>  I would prefer hydration data to be in a standard JSON-API format, and not have to know about the way that redux-json-api. 

Seems like a good thought on this subject, but like you mention your self we would like not to pollute the global api / namespace with non CRUD api's (helper functions is another thing but not for ths pr to discuss ofc)

If you write up a solution i'll be happy to look into this later. 

So create new PR, Write breaking test, and then we look at the implementaion :)

on a side note, we would love to hear if you are gonna try out `2.0` while developing this if you find any bugs :) we are our self just still testing it.

**Comment by berfarah** [comment]
Continued here https://github.com/dixieio/redux-json-api/pull/129

**Pull request closed without merging**
